
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 22324223
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      target: runner      # имя стадии рантайма в вашем Dockerfile
    restart: always
    env_file:
      - .env              # все переменные подхватятся из файла
    ports:
      - "${PORT}:3003"
    depends_on:
      - db

volumes:
  db-data:
