export const TYPES = {
  Application: Symbol.for('Application'),
  ILogger: Symbol.for('ILogger'),
  ConfigService: Symbol.for('ConfigService'),
  PrismaService: Symbol.for('PrismaService'),
  ExeptionFilter: Symbol.for('ExeptionFilter'),
  PassportConfig: Symbol.for('PassportConfig'),
  UserController: Symbol.for('UserController'),
  UserService: Symbol.for('UserService'),
  UsersRepository: Symbol.for('UsersRepository'),
  ProgramController: Symbol.for('ProgramController'),
  ProgramService: Symbol.for('ProgramService'),
  ProgramRepository: Symbol.for('ProgramRepository'),
  DayController: Symbol.for('DayController'),
  DayService: Symbol.for('DayService'),
  DayRepository: Symbol.for('DayRepository'),
  ExerciseController: Symbol.for('ExerciseController'),
  ExerciseService: Symbol.for('ExerciseService'),
  ExerciseRepository: Symbol.for('ExerciseRepository'),
  TelegramController: Symbol.for('TelegramController'),
  TelegramRepository: Symbol.for('TelegramRepository'),
  TelegramService: Symbol.for('TelegramService'),
};
